{"text": "2022-07-13T00:47:46.870351+0300 | ERROR      | An error has been caught in function 'call', process 'MainProcess' (15648), thread 'MainThread' (10724):\nTraceback (most recent call last):\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\bot.py\", line 72, in <module>\n    bot.run(config.get_token)\n    │   │   │      └ <property object at 0x000002A689BA4860>\n    │   │   └ <_config.Config object at 0x000002A6883DFAF0>\n    │   └ <function Client.run at 0x000002A688F01900>\n    └ <nextcord.ext.commands.bot.Bot object at 0x000002A689B7FA30>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\client.py\", line 796, in run\n    loop.run_forever()\n    │    └ <function ProactorEventLoop.run_forever at 0x000002A6881F0EE0>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\windows_events.py\", line 321, in run_forever\n    super().run_forever()\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n    self._run_once()\n    │    └ <function BaseEventLoop._run_once at 0x000002A688142290>\n    └ <ProactorEventLoop running=True closed=False debug=False>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n    handle._run()\n    │      └ <function Handle._run at 0x000002A6880D1AB0>\n    └ <Handle <TaskStepMethWrapper object at 0x000002A68D743670>()>\n\n  File \"C:\\Users\\phili\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n    │    │            │    │           │    └ <member '_args' of 'Handle' objects>\n    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x000002A68D743670>()>\n    │    │            │    └ <member '_callback' of 'Handle' objects>\n    │    │            └ <Handle <TaskStepMethWrapper object at 0x000002A68D743670>()>\n    │    └ <member '_context' of 'Handle' objects>\n    └ <Handle <TaskStepMethWrapper object at 0x000002A68D743670>()>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\client.py\", line 445, in _run_event\n    await coro(*args, **kwargs)\n          │     │       └ {}\n          │     └ (<nextcord.interactions.Interaction object at 0x000002A689EF32A0>,)\n          └ <bound method Client.on_interaction of <nextcord.ext.commands.bot.Bot object at 0x000002A689B7FA30>>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1872, in on_interaction\n    await self.process_application_commands(interaction)\n          │    │                            └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          │    └ <function Client.process_application_commands at 0x000002A688F031C0>\n          └ <nextcord.ext.commands.bot.Bot object at 0x000002A689B7FA30>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\client.py\", line 1892, in process_application_commands\n    await app_cmd.call_from_interaction(interaction)\n          │       │                     └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          │       └ <function BaseApplicationCommand.call_from_interaction at 0x000002A688E5B880>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2045, in call_from_interaction\n    await self.call(self._state, interaction)  # type: ignore\n          │    │    │    │       └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          │    │    │    └ <nextcord.state.ConnectionState object at 0x000002A689DE2BC0>\n          │    │    └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n          │    └ <function SlashApplicationCommand.call at 0x000002A688EAC1F0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 2397, in call\n    await self.call_slash(state, interaction, option_data)\n          │    │          │      │            └ [{'value': 'речь', 'type': 3, 'name': 'do'}]\n          │    │          │      └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          │    │          └ <nextcord.state.ConnectionState object at 0x000002A689DE2BC0>\n          │    └ <function SlashCommandMixin.call_slash at 0x000002A688E5ADD0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 1514, in call_slash\n    await self.invoke_callback_with_hooks(state, interaction, **kwargs)\n          │    │                          │      │              └ {'do': 'речь'}\n          │    │                          │      └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          │    │                          └ <nextcord.state.ConnectionState object at 0x000002A689DE2BC0>\n          │    └ <function CallbackMixin.invoke_callback_with_hooks at 0x000002A688E59EA0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\venv\\lib\\site-packages\\nextcord\\application_command.py\", line 824, in invoke_callback_with_hooks\n    await self(interaction, *args, **kwargs)\n          │    │             │       └ {'do': 'речь'}\n          │    │             └ ()\n          │    └ <nextcord.interactions.Interaction object at 0x000002A689EF32A0>\n          └ <nextcord.application_command.SlashApplicationCommand object at 0x000002A689FA7700>\n\n> File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 177, in call\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 154, in callback\n    name=\"gm\",\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py\", line 38, in change_speech\n    new_speech\n    └ <coroutine object MasterCommands.__get_new_topic_or_speech at 0x000002A68CA96030>\n\n  File \"C:\\Users\\phili\\PycharmProjects\\GuildsBot\\SlaveBOTOrigins\\GuildsManager.py\", line 89, in change_row\n    cur.execute(query)\n    │   │       └ \"\\n\\t\\t\\tUPDATE guild\\n\\t\\t\\tSET speech = <coroutine object MasterCommands.__get_new_topic_or_speech at 0x000002A68CA96030>\\n...\n    │   └ <method 'execute' of 'sqlite3.Cursor' objects>\n    └ <sqlite3.Cursor object at 0x000002A689AB3DC0>\n\nsqlite3.OperationalError: near \"<\": syntax error\n", "record": {"elapsed": {"repr": "0:00:44.816343", "seconds": 44.816343}, "exception": {"type": "OperationalError", "value": "near \"<\": syntax error", "traceback": true}, "extra": {}, "file": {"name": "master.py", "path": "C:\\Users\\phili\\PycharmProjects\\GuildsBot\\cogs\\master.py"}, "function": "call", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 177, "message": "An error has been caught in function 'call', process 'MainProcess' (15648), thread 'MainThread' (10724):", "module": "master", "name": "cogs.master", "process": {"id": 15648, "name": "MainProcess"}, "thread": {"id": 10724, "name": "MainThread"}, "time": {"repr": "2022-07-13 00:47:46.870351+03:00", "timestamp": 1657662466.870351}}}
